version: '3'

services:
  api-gateway:
    build: ./api_gateways
    ports:
      - "3000:3000"
    depends_on:
      - js_service
      - python_service

  user-service:
    build: ./js_service
    ports:
      - "3001:3001"

  order-service:
    build: ./python_service
    ports:
      - "3002:3002"
